### PR TITLE
Add ability and script to test yank-examples

### PR DESCRIPTION
**Pull request by Lnaden**

### CODE REVIEW

**Comment by Lnaden** [comment]
Fixes #25

**Comment by jchodera** [comment]
Looks great, but should this be `test_examples.py`?

**Comment by Lnaden** [comment]
Oh, yes, I'll need to rename that. We have a larger issue where the minimize/iterate step is ultra slow on the CPU that is travis. Not sure how to speed it up

**Comment by andrrizzi** [comment]
Are the structures good enough to just skip minimization altogether for tests?

Also, if it can make your life easier, you can just `yaml.load(script)`, modify as a dictionary and then `yaml.dump` the dictionary instead of using `regex`. Or simply call `YamlBuilder(dictionary).build_experiments()`. For loading/dumping you may need to use `yamlbuild.YamlLoader` and `yamlbuild.YamlDumper`.

**Comment by Lnaden** [comment]
@andrrizzi Good idea, we can tweak once I figure out the speed issues.

I'm not sure skipping minimization is such a good idea since we want the examples to run with a little changes to the functionality as possible to show the whole thing is working. As a stop-gap, I put in code to set `minimize_max_iterations: 1`, but even that doesn't look like it works.

For the SMILES string tests (which are generally skipped), we may want to minimize since the structures are not going to be in any minimized position, although for small molecules its less important.

**Comment by andrrizzi** [comment]
> I'm not sure skipping minimization is such a good idea since we want the examples to run with a little changes to the functionality as possible

Yeah, good point! Maybe we should just run these tests on Jenkins/cluster (when that will be set up).

**Comment by Lnaden** [comment]
I think that might be the best idea. Even if we don't run the tests on travis, I want to leave the script in here and keep updating it as we add new tests

**Comment by jchodera** [comment]
> Yeah, good point! Maybe we should just run these tests on Jenkins/cluster (when that will be set up).

Still working on getting Jenkins back up!

Another possibility is to add a faster minimizer, like the [Fire minimizer](https://github.com/choderalab/openmmtools/issues/85) I'm working on in`openmoltools`. It's not essential for 1.0, but it's something where we can punt on travis tests until then.

**Comment by Lnaden** [comment]
A faster minimizer is on the list as well. But I think the solution for now is to just disable running the tests (keep the file), and reenable them at a future date.

**Comment by jchodera** [comment]
I think we're in agreement!

**Pull request merged**
